// playground/frontend/src/scripts/containers/RouterJS.jsx
import { i18n } from 'basx';
import store from 'scripts/store';
import PropTypes from 'prop-types';
import React, { Suspense } from 'react';
import routes from 'scripts/store/routes';
import useStore from 'diox/connectors/react';
import Loader from 'scripts/components/Loader';

const [useCombiner] = useStore(store); // eslint-disable-line

const propTypes = {
  locale: PropTypes.instanceOf(Object).isRequired,
};

/**
 * App router.
 */
export default function RouterJS(props) {
  const { locale } = props;
  const [route] = useCombiner('router', (newState) => newState.route);

  let currentPage = null;
  if (routes[route] !== undefined) {
    const Component = React.lazy(routes[route]);
    currentPage = <Component translate={i18n(locale)} />;
  }

  return (
    <Suspense fallback={<Loader />}>
      {currentPage}
    </Suspense>
  );
}

RouterJS.propTypes = propTypes;
RouterJS.defaultProps = {};
RouterJS.displayName = 'RouterJS';

// playground/vue/src/scripts/containers/RouterJS.vue
<template>
  <component
    :is="componentName"
    v-if="componentName !== undefined"
    :translate="translate"
  />
</template>

<script>
import { i18n } from 'basx';
import store from 'scripts/store';
import routes from 'scripts/store/routes';
import useStore from 'diox/connectors/vue';

const [useCombiner] = useStore(store);
const lazyComponents = Object.keys(routes).reduce((mapping, route, index) => ({
  ...mapping,
  [route]: `Component${index}`,
}), {});

/**
 * App router.
 */
export default useCombiner('router', {
  name: 'RouterJS',
  components: Object.keys(routes).reduce((components, route) => ({
    ...components,
    [lazyComponents[route]]: routes[route],
  }), {}),
  props: {
    locale: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      route: '',
    };
  },
  computed: {
    translate() {
      return i18n(this.locale);
    },
    componentName() {
      return routes[this.route];
    },
  },
});
</script>
