// playground/frontend/src/scripts/containers/Router.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import * as routes from 'scripts/store/routes';
  import useCombiner from 'scripts/store/useCombiner';
  import Loader from 'scripts/components/Loader.svelte';

  let component: Any = { default: Loader };
  type Any = any; // eslint-disable-line
  export let locale: Record<string, string>;
  const router = useCombiner<Any>('router', (newState: Any) => newState);
  const unsubscribe = router.subscribe(async (newState) => {
    if ((routes as Any)[newState.route]) {
      component = await (routes as Any)[newState.route]();
    } else {
      component = null;
    }
  });
  onDestroy(unsubscribe);
</script>

{#if component !== null}
  <svelte:component this={component.default} {locale} />
{/if}

// playground/frontend/src/scripts/containers/Router.vue
<template>
  <component
    :is="componentName"
    v-if="componentName !== undefined"
    :translate="translate"
  />
</template>

<script lang="ts">
import { i18n } from 'basx';
import store from 'scripts/store';
import routes from 'scripts/store/routes';
import useStore from 'scripts/store/useStore';

interface Locale {
  [label: string]: string;
}

const [useCombiner] = useStore(store); // eslint-disable-line
const lazyComponents = Object.keys(routes).reduce((mapping, route, index) => ({
  ...mapping,
  [route]: `Component${index}`,
}), {}) as { [name: string]: string; };

/**
 * App router.
 */
export default useCombiner('router', { // eslint-disable-line
  name: 'Router',
  components: Object.keys(routes).reduce((components, route) => ({
    ...components,
    [lazyComponents[route]]: routes[route],
  }), {}),
  props: {
    locale: {
      type: Object,
      required: true,
    },
  },
  computed: {
    translate(): (label: string) => string {
      return i18n((this as unknown as { locale: Locale; }).locale);
    },
    componentName(): string {
      return lazyComponents[this.route];
    },
  },
});
</script>
