// playground/frontend/src/scripts/containers/Router.vue
<template>
  <component
    :is="componentName"
    v-if="componentName !== undefined"
    :translate="translate"
  />
</template>

<script lang="ts">
import { i18n } from 'basx';
import store from 'scripts/store';
import routes from 'scripts/store/routes';
import useStore from 'scripts/store/useStore';

interface Locale {
  [label: string]: string;
}

const [useCombiner] = useStore(store); // eslint-disable-line
const lazyComponents = Object.keys(routes).reduce((mapping, route, index) => ({
  ...mapping,
  [route]: `Component${index}`,
}), {}) as { [name: string]: string; };

/**
 * App router.
 */
export default useCombiner('router', { // eslint-disable-line
  name: 'Router',
  components: Object.keys(routes).reduce((components, route) => ({
    ...components,
    [lazyComponents[route]]: routes[route],
  }), {}),
  props: {
    locale: {
      type: Object,
      required: true,
    },
  },
  computed: {
    translate(): (label: string) => string {
      return i18n((this as unknown as { locale: Locale; }).locale);
    },
    componentName(): string {
      return lazyComponents[this.route];
    },
  },
});
</script>

// playground/frontend/src/scripts/containers/Router.tsx
import { i18n } from 'basx';
import store from 'scripts/store';
import React, { Suspense } from 'react';
import routes from 'scripts/store/routes';
import useStore from 'diox/connectors/react';
import Loader from 'scripts/components/Loader';
import PropTypes, { InferProps } from 'prop-types';

type LazyComponent = () => Promise<{
  default: React.ComponentType<{
    translate: (label: string, values: Record<string, string>) => string
  }>
}>;

const [useCombiner] = useStore(store); // eslint-disable-line react-hooks/rules-of-hooks

const propTypes = {
  locale: PropTypes.instanceOf(Object).isRequired,
};

/**
 * App router.
 */
export default function Router(props: InferProps<typeof propTypes>): JSX.Element {
  const { locale } = props;
  const [route] = useCombiner('router', (newState: { route: string; }) => newState.route);

  let currentPage = null;
  if (routes[route] !== undefined) {
    const Component = React.lazy(routes[route] as LazyComponent) as JSXElement;
    currentPage = <Component translate={i18n(locale as Record<string, string>)} />;
  }

  const AnySuspense = Suspense as JSXElement;
  return (
    <AnySuspense fallback={<Loader /> as JSXElement}>
      {currentPage}
    </AnySuspense>
  );
}

Router.propTypes = propTypes;
Router.defaultProps = {};
Router.displayName = 'Router';
