// playground/react/src/scripts/pages/Home.tsx
import * as React from 'react';
import Message from 'scripts/components/Message';
import PropTypes, { InferProps } from 'prop-types';

const propTypes = {
  translate: PropTypes.func.isRequired,
};

/**
 * Home page.
 */
export default function Home(props: InferProps<typeof propTypes>): JSX.Element {
  const { translate } = props;

  return (
    <Message label={translate('LABEL_TEST')} />
  );
}

Home.propTypes = propTypes;
Home.defaultProps = {};
Home.displayName = 'Home';

// playground/vue/src/scripts/pages/Home.vue
<template>
  <message :label="translate('LABEL_TEST')" />
</template>

<script lang="ts">
import Message from 'scripts/components/Message.vue';

/**
 * Home page.
 */
export default {
  name: 'Home',
  components: {
    Message,
  },
  props: {
    translate: {
      type: Function,
      required: true,
    },
  },
};
</script>
